name: setup

inputs:
  NPOTAG_PACKAGE_CLOUD_KEY:
    required: true
  NPO_PLAYER_BITMOVIN_LICENCE_KEY:
    required: true
  NPO_PLAYER_BITMOVIN_ANALYTICS_KEY:
    required: true
  TOKEN_ISSUER_START:
    required: true
  TOKEN_ISSUER_PLUS:
    required: true
  TOKEN_SIGNATURE_START_DEV:
    required: true
  TOKEN_SIGNATURE_PLUS_DEV:
    required: true
  TOKEN_SIGNATURE_START_ACC:
    required: true
  TOKEN_SIGNATURE_PLUS_ACC:
    required: true
  TOKEN_SIGNATURE_START_PROD:
    required: true
  TOKEN_SIGNATURE_PLUS_PROD:
    required: true
  STORE_FILE_PATH:
    required: true
  STORE_FILE_PASSWORD:
    required: true
  STORE_FILE_ALIAS:
    required: true
  STORE_FILE_ALIAS_PASSWORD:
    required: true
  STORE_FILE_BASE64:
    required: true
  PACKAGES_USER:
    required: true
  PACKAGES_TOKEN:
    required: true

runs:
  using: composite
  steps:
    - name: Setup Java
      uses: actions/setup-java@v4.0.0
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - run: |
        echo "npotag_package_cloud_key=${{ inputs.NPOTAG_PACKAGE_CLOUD_KEY }}" >> local.properties
        echo "your_player_license_key_here=${{ inputs.NPO_PLAYER_BITMOVIN_LICENCE_KEY }}" >> local.properties
        echo "your_analytics_license_key_here=${{ inputs.NPO_PLAYER_BITMOVIN_ANALYTICS_KEY }}" >> local.properties
        echo "token_issuer_start=${{ inputs.TOKEN_ISSUER_START }}" >> local.properties
        echo "token_issuer_plus=${{ inputs.TOKEN_ISSUER_PLUS }}" >> local.properties
        echo "token_signature_start_dev=${{ inputs.TOKEN_SIGNATURE_START_DEV }}" >> local.properties
        echo "token_signature_plus_dev=${{ inputs.TOKEN_SIGNATURE_PLUS_DEV }}" >> local.properties
        echo "token_signature_start_acc=${{ inputs.TOKEN_SIGNATURE_START_ACC }}" >> local.properties
        echo "token_signature_plus_acc=${{ inputs.TOKEN_SIGNATURE_PLUS_ACC }}" >> local.properties
        echo "token_signature_start_prod=${{ inputs.TOKEN_SIGNATURE_START_PROD }}" >> local.properties
        echo "token_signature_plus_prod=${{ inputs.TOKEN_SIGNATURE_PLUS_PROD }}" >> local.properties
        echo "storeFile=${{ inputs.STORE_FILE_PATH }}" >> local.properties
        echo "storePassword=${{ inputs.STORE_FILE_PASSWORD }}" >> local.properties
        echo "keyAlias=${{ inputs.STORE_FILE_ALIAS }}" >> local.properties
        echo "keyPassword=${{ inputs.STORE_FILE_ALIAS_PASSWORD }}" >> local.properties
        echo "github_packages_user=${{ inputs.PACKAGES_USER }}" >> local.properties
        echo "github_packages_token=${{ inputs.PACKAGES_TOKEN }}" >> local.properties
      shell: bash
    - run: |
        mkdir signing
        echo "${{ inputs.STORE_FILE_BASE64 }}" >> signing/sample_app_keystore.txt
        base64 --decode signing/sample_app_keystore.txt > signing/sample_app_keystore.jks
      shell: bash